# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c3722d4496a9670f6e750225a1acbc8180987f32a3ad3a04b55bde4f2712001b1a8b0de55e0e5f8cea5c6252d99113273c3d35b445ec14e7ad6a1715c7d642e

test:
  secret_key_base: 086704e384fb9d4717c2ef194e14e23e2c61811be283e2bcf7a10c4c23885c5d1ffc69f7efd0cba314536a3bb97d4d8d768c8a34198909a7b55e24c8fc1661bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
