# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a746a8eae26f524c2cbb7ac358246ee26e77312d40b340db3eea7e4d7e87c8ab1c532ab2d847fef1a13c4246b2dc4b6d329fc42a17f19240ee317f71c54666d2

test:
  secret_key_base: b69cb7b707fb89032dd293e14e29542c56ce39124419a4cf3955d04816d3f9989603a7156f15222e24711bc10bd649bdc7bcfed574c2bda776c08c6d439e0b92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
