# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe2664d9e5245341eb66635cf55e4c3f3708d183ebd3b3206990e6bb4bb18035fea14675d291d1fcd94230061a6cec859c5bf5f3f86b44420dfe9dec4ecb519e

test:
  secret_key_base: e950d17c27b88a76dc80f4ddd03015c2a65f40a6d52a088e09fbe9aefbb992dad491675e54b8c42388414bff1ace6f9f5131e88418595de524919c1109097d86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
