# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29e1279be060ea58cbf393429967c54c7a266a40ce4a808ea8398123adf4afeb4e4bba05a2fe0b3afc98da020f8157a8f93d0b9cdcbd571a0bf447b15b656b3

test:
  secret_key_base: 10ee60e59fd4518c7c37ac8e1a50456093ce56f17f713c91f7daf07c3e6b45be6899e06d2bf3179d3e0636231ec81d841c04a0cd7057a1cfc728fe72b01f44b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
